### ISSUE TITLE
Difference between existing packages?

### ISSUE THREAD

**Issue by chengchingwen** [cjdoris/PythonIO.jl#2]
Hi, I just notice this package and I'm wondering about what's the difference between this package and those existing packages like [Pickle.jl](https://github.com/chengchingwen/Pickle.jl) and [NPZ.jl](https://github.com/fhs/NPZ.jl)? And maybe it's worth directly depending on them?

**Comment by cjdoris** [comment]
This is unregistered and very experimental!

Partly I don't particularly like the API of NPZ.jl and partly putting them in the same place allows some useful behaviour, like you can reuse the Python parser to implement reading npy files, and the pickle parser allows parsing a wider range of npy files, e.g. ones containing strings.
